### ISSUE TITLE
interferes with use of '/' on certain websites to place cursor into site-specific search textbox

### ISSUE THREAD

**Issue by bennnnn** [peterdotjs/quick-find#14]
Google, for example, uses this in search results window to ease creation of new search.

I think I'd like to be able to turn off use of '/' completely, I only need link-search mode.

I can be more specific later

**Comment by peterdotjs** [comment]
I'd like to keep that feature on - as that is the original key used from Firefox. Users can change the key being used in the shortcut keys menu. Also there already is a link-search only shortcut key.

**Comment by bennnnn** [comment]
concern about diverging from FF implementation did concern me.

if you'll notice, changing the shortcut doesn't remove or disable the '/'
hotkey quicksearch shortcut

On Mon, Jul 6, 2015 at 12:56 PM, Peter J. Shin <notifications@github.com>
wrote:

> I'd like to keep that feature on - as that is the original key used from
> Firefox. Users can change the key being used in the shortcut keys menu.
> Also there already is a link-search only shortcut key.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/peterdotjs/quick-find/issues/14#issuecomment-118924042>
> .
>



-- 
....A triangle was an improvement to the square wheel. It eliminated one
bump.
